### ISSUE TITLE
Convert ROS2 messages into protobuf messages in C++ on the fly

### ISSUE THREAD

**Issue by LastStarDust** [eclipse-ecal/rosidl_typesupport_protobuf#21]
@FlorianReimold 
Hello again!
As you might recall, I was able to use this package to automatically convert ROS .msg files into protobuf .proto files.
This package and your help saved me a lot of time and trouble. Thank you again so much.

I was wondering if there is any portion of this codebase that I can use to convert from ROS messages to protobuf messages in C++ on the fly, using the definitions that I generated beforehand.

I do not need any facility to serialize/deserialize. I just would like to make a templated function where a ROS2 message object enters and a protobuf message object exits.

Regards
Giorgio

**Comment by FlorianReimold** [comment]
I am not really sure what your goal is, but I can guess.

If you want to write a C++ project that uses the autogenerated C++ `.pb.h` / `.pb.cpp` files coming from a `.msg` file at compile time: Sure, that is possible and exactly what this package is for. But it depends on your build system how you solve it. The ROS colcon build system has this pre-solved for you (obviously). If you want to use native CMake, you may probably have to write the cmake script yourself, which convertes the `.msg` files to `.proto` first and then invokes `protoc` to generate the cpp files from those. pretty much any build system for C++ has the ability to invoke shell / batch commands, so you use that technique to convert `.msg` -> `.proto` -> `.pb.h

If you want to load `.msg` files at runtime and then create protobuf messages fro them all at runtime: This is going to be difficult. C++ is a compiled language, so not having the declarations of your protobuf files at compile time will force you to use the protobuf reflection API to work with dynamic messages that are not known at compile time. And first converting from .msg to the .proto files would probably force you to invoke this converter with a system command or include an entire python environment in your c++ application. I don't know what you are trying to do, but this is a lot of work and probably not worth it.

If you want to dynamically convert between protobuf serialized messages and .msg serialized messages without knowing about them at compile time I have bad news for you: .msg serialization does not exist, which is the reason why all of these typesupports even exist. A .msg file only describes the schema of a message, but how that data is serialized is defined by the typesupport. This typesupport uses protobuf for serialization and other typsupports use other techniques for serialization. If you can convert between two of them dynamically at runtime depends on what information you still have at runtime. For protobuf this is possible through the reflection API, but you will have to have the protobuf descriptor string available.

**Comment by LastStarDust** [comment]
Thank you for the quick reply and sorry if I did not explain my goals more clearly.

I already have all the machinery in place for generating a `.proto` file and the relative `.pb.h` and `pb.c` source at compile time, starting from the `.msg` definition. BTW I do it by leveraging the CMake `generate_protobuf_cpp` function.

So at runtime, I can easily construct both the ROS2 message object and the correspondent protobuf message object. These two objects should have the same number of members with "roughly"  the same type because they were autogenerated starting from the same `.msg` definition.

I just need a way to assign to each member of the protobuf message, the value of the corresponding member of ROS2 message. 

For example if `ros::Foo` is a ROS2 message with a single `int32` member called `bar`, and `protobuf::Foo` is the corresponding protobuf message with an int member with the same name, I would like to have a generic (templated?) function `convert` to do something like this:

```
ros::Foo ros_message;
message.bar = 1;
protobuf::Foo protobuf_message = convert(ros_message);
```
This is pseudocode so the syntax is pretty random, but I hope you got the idea.

PS At runtime, the ROS message object is constructed using the default ROS2 type support (that I think is `rmw_fastrtps_cpp`) and not `rosidl_typesupport_protobuf`.

**Comment by LastStarDust** [comment]
Another way to put it is: would it be possible to extract from this package only the protobuf message introspection part so that I can iterate over all the fields of a protobuf message and assign them the corresponding value of a ROS message?
All of this while keeping the ROS2 default typesupport for internode communication.

The ultimate reason I want to do this, is because our ROS system has to interface with an external software that uses protobuf as a communication protocol.

**Comment by FlorianReimold** [comment]
Well, the rosidl_typesupport_protobuf (and probably all the other typesupports as well) solve that again with autocode generation:
https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/tree/master/rosidl_typesupport_protobuf_cpp/resource

That's not generic at runtime though, it is autogenerated code that is statically compiled into your typesupport. You have to re-compile your typesupport for any message you add or modify, which is one of the major downsides of those ROS static typesupports, if you ask me.

**Comment by LastStarDust** [comment]
Thank you for the link. I had already a hunch that I had to use some sort of code generation.

**Comment by FlorianReimold** [comment]
> Another way to put it is: would it be possible to extract from this package only the protobuf message introspection part so that I can iterate over all the fields of a protobuf message and assign them the corresponding value of a ROS message?

That's a protobuf feature, you get that for free when using protobuf. We make heavy use of that feature in our [eCAL](https://github.com/eclipse-ecal/ecal) Middleware. But the reflection API is much less performant and way more difficult to work with. You must have your ros messages available anyways at compile time, so there isn't a reason to not have the proto files at compile time, too.
Then maybe extract the code from the typesupport again, or just quickly write it by hand, if the .msg files are stable.

**Comment by LastStarDust** [comment]
Thank you again for the discussion. This should be enough to get me going.
