### ISSUE TITLE
[Enhancement] Order of `import` statements is random

### ISSUE THREAD

**Issue by LastStarDust** [eclipse-ecal/rosidl_typesupport_protobuf#25]
Hello. Sorry to bother you again.
I noticed that the order of the `import` statements in the .proto definitions is randomly changing every time the software is run.

Run once and it may be:
```protobuf
import "def1.proto";
import "def2.proto";
import "def3.proto";
```
Run another time without any change and it may be:
```protobuf
import "def3.proto";
import "def1.proto";
import "def2.proto";
```

I know that this software is not maintained anymore, so I am not asking you to modify it, but could you please point out where in the source code is the part dealing with `import` list generation, so that I can make a pull request?

**Comment by FlorianReimold** [comment]
Sure, we are happy to accept PRs! 🙌

Here is the line of code that creates those imports:

https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/blob/132668ae385163ee8b45ce45a9022654e5c77666/rosidl_adapter_proto/resource/idl.proto.em#L83

The lines above create the list of files to import, so probably you only have to add some line to sort them by name.

**Comment by tfoote** [comment]
@LastStarDust I tried to address this in #28

**Comment by LastStarDust** [comment]
@tfoote Thank you so much for providing a solution.
@FlorianReimold You can close this Issue whenever PR #28 is merged.
