### ISSUE TITLE
Question: Are there plans to add tests?

### ISSUE THREAD

**Issue by r7vme** [eclipse-ecal/rosidl_typesupport_protobuf#8]
Hello, thanks for this project!

Do you have any plans to cover code with tests? Are you open for contributions (e.g. starting w/ gtests for some C++ functions)?

Code quality feels on a very good level, so I suspect you may have some internal (non-open source) tests already.

Thanks, Roman

**Comment by brakmic-aleksandar** [comment]
Tests aren't planned for this repo at this current moment, but we are open for contributions. :)

**Comment by r7vme** [comment]
@brakmic-aleksandar thanks, I'll try to submit some tests
